### ISSUE TITLE
EtekCity outlets

### ISSUE THREAD

**Issue by matt-desmarais** [cerosx/RPI.PIHome2.0-GUI-Frontend#4]
I am trying to control one of the etekcity outlets. 
I am thinking i may have to modify some code and would like to know where you actually send the signal, is it in apiController?

The signals sent by my remote I got this from using my sdr and rtl_433

Outlet 1
01010101 00110101 00000011  on
01010101 00110101 00001100  off

Outlet 2
01010101 00011101 00000011 on
01010101 00011101 00001100 off

Any help would be greatly appreciated

**Comment by tklucis** [comment]
You can use sniffer and code sender from [this](https://www.samkear.com/hardware/control-power-outlets-wirelessly-raspberry-pi) project.

**Comment by matt-desmarais** [comment]
Thank you! I also found the info here http://timleland.com/wireless-power-outlets/ with alot of good info hidden in the comments.
Although i couldnt get RFSniffer to work, i figured it out.
What I had to do was take the binary codes and convert them to decimal then use codesend with that number and put the values in toggle.php
